import type { DesignTemplate } from "@/types";

/**
 * Invite image builder templates. Each has background, default text slots, aspect ratio.
 * Positions/sizes are normalized 0–1 for canvas (width/height).
 */
export const DESIGN_TEMPLATES: DesignTemplate[] = [
  {
    id: "wedding-floral",
    name: "Wedding floral",
    eventType: "wedding",
    aspectRatio: 4 / 5,
    canvas: { width: 1080, height: 1350 },
    background: {
      type: "gradient",
      from: "#fdf8f3",
      to: "#f5ebe0",
    },
    textLayers: [
      {
        id: "title",
        defaultText: "We're Getting Married",
        x: 0.5,
        y: 0.22,
        fontSize: 48,
        fontFamily: "Cormorant Garamond",
        fontWeight: "600",
        color: "#2c1810",
        textAlign: "center",
        maxWidth: 0.85,
      },
      {
        id: "date",
        defaultText: "Saturday, June 15, 2026",
        x: 0.5,
        y: 0.38,
        fontSize: 22,
        fontFamily: "Cormorant Garamond",
        color: "#5c4a3d",
        textAlign: "center",
        maxWidth: 0.85,
      },
      {
        id: "tagline",
        defaultText: "Together with their families",
        x: 0.5,
        y: 0.52,
        fontSize: 18,
        fontFamily: "Cormorant Garamond",
        color: "#7d6b5c",
        textAlign: "center",
        maxWidth: 0.85,
      },
    ],
    objectSlots: [
      { id: "top-deco", assetId: "divider-line", x: 0.5, y: 0.08, scale: 0.55, default: true },
      { id: "bottom-deco", assetId: "divider-line", x: 0.5, y: 0.92, scale: 0.55, default: true },
    ],
    photoSlot: { x: 0.5, y: 0.68, width: 0.32, height: 0.32, shape: "circle" },
  },
  {
    id: "birthday-minimal",
    name: "Birthday minimal",
    eventType: "birthday",
    aspectRatio: 4 / 5,
    canvas: { width: 1080, height: 1350 },
    background: {
      type: "solid",
      color: "#1a1a2e",
    },
    textLayers: [
      {
        id: "title",
        defaultText: "You're Invited",
        x: 0.5,
        y: 0.28,
        fontSize: 42,
        fontFamily: "Cormorant Garamond",
        fontWeight: "600",
        color: "#ffffff",
        textAlign: "center",
        maxWidth: 0.9,
      },
      {
        id: "date",
        defaultText: "Saturday • 3:00 PM",
        x: 0.5,
        y: 0.45,
        fontSize: 20,
        fontFamily: "Cormorant Garamond",
        color: "#e0e0e0",
        textAlign: "center",
        maxWidth: 0.9,
      },
      {
        id: "tagline",
        defaultText: "Celebrate with us",
        x: 0.5,
        y: 0.58,
        fontSize: 18,
        fontFamily: "Cormorant Garamond",
        color: "#b0b0b0",
        textAlign: "center",
        maxWidth: 0.9,
      },
    ],
    objectSlots: [
      { id: "corner", assetId: "corner-minimal", x: 0.08, y: 0.08, scale: 0.32, default: true },
    ],
    photoSlot: { x: 0.5, y: 0.72, width: 0.38, height: 0.38, shape: "roundedRect" },
  },
  {
    id: "party-bold",
    name: "Party bold",
    eventType: "party",
    aspectRatio: 4 / 5,
    canvas: { width: 1080, height: 1350 },
    background: {
      type: "gradient",
      from: "#2d1b4e",
      to: "#1a0a2e",
    },
    textLayers: [
      {
        id: "title",
        defaultText: "Party Night",
        x: 0.5,
        y: 0.25,
        fontSize: 52,
        fontFamily: "Cormorant Garamond",
        fontWeight: "700",
        color: "#ffd700",
        textAlign: "center",
        maxWidth: 0.9,
      },
      {
        id: "date",
        defaultText: "Friday 9 PM",
        x: 0.5,
        y: 0.42,
        fontSize: 24,
        fontFamily: "Cormorant Garamond",
        color: "#ffffff",
        textAlign: "center",
        maxWidth: 0.9,
      },
      {
        id: "tagline",
        defaultText: "Dress to impress",
        x: 0.5,
        y: 0.54,
        fontSize: 18,
        fontFamily: "Cormorant Garamond",
        color: "#e0c0ff",
        textAlign: "center",
        maxWidth: 0.9,
      },
    ],
    objectSlots: [
      { id: "divider", assetId: "divider-line", x: 0.5, y: 0.68, scale: 0.5, default: true },
    ],
  },
  {
    id: "generic-elegant",
    name: "Elegant",
    eventType: "generic",
    aspectRatio: 4 / 5,
    canvas: { width: 1080, height: 1350 },
    background: {
      type: "gradient",
      from: "#faf9f7",
      to: "#ebe8e4",
    },
    textLayers: [
      {
        id: "title",
        defaultText: "You're Invited",
        x: 0.5,
        y: 0.26,
        fontSize: 44,
        fontFamily: "Cormorant Garamond",
        fontWeight: "600",
        color: "#333333",
        textAlign: "center",
        maxWidth: 0.85,
      },
      {
        id: "date",
        defaultText: "Save the date",
        x: 0.5,
        y: 0.42,
        fontSize: 20,
        fontFamily: "Cormorant Garamond",
        color: "#555555",
        textAlign: "center",
        maxWidth: 0.85,
      },
      {
        id: "tagline",
        defaultText: "We hope you can join us",
        x: 0.5,
        y: 0.55,
        fontSize: 18,
        fontFamily: "Cormorant Garamond",
        color: "#777777",
        textAlign: "center",
        maxWidth: 0.85,
      },
    ],
    objectSlots: [
      { id: "top", assetId: "divider-line", x: 0.5, y: 0.1, scale: 0.5, default: true },
      { id: "bottom", assetId: "divider-line", x: 0.5, y: 0.9, scale: 0.5, default: true },
    ],
  },
  {
    id: "baby-shower-soft",
    name: "Baby shower",
    eventType: "baby",
    aspectRatio: 4 / 5,
    canvas: { width: 1080, height: 1350 },
    background: {
      type: "gradient",
      from: "#f0e6f6",
      to: "#e8d4f0",
    },
    textLayers: [
      {
        id: "title",
        defaultText: "Baby Shower",
        x: 0.5,
        y: 0.2,
        fontSize: 46,
        fontFamily: "Cormorant Garamond",
        fontWeight: "600",
        color: "#4a3a5c",
        textAlign: "center",
        maxWidth: 0.85,
      },
      {
        id: "date",
        defaultText: "Join us to celebrate",
        x: 0.5,
        y: 0.36,
        fontSize: 22,
        fontFamily: "Cormorant Garamond",
        color: "#6b5b7b",
        textAlign: "center",
        maxWidth: 0.85,
      },
      {
        id: "tagline",
        defaultText: "With love",
        x: 0.5,
        y: 0.5,
        fontSize: 18,
        fontFamily: "Cormorant Garamond",
        color: "#8a7a9a",
        textAlign: "center",
        maxWidth: 0.85,
      },
    ],
    objectSlots: [
      { id: "divider", assetId: "divider-line", x: 0.5, y: 0.62, scale: 0.5, default: true },
    ],
    photoSlot: { x: 0.5, y: 0.78, width: 0.28, height: 0.28, shape: "circle" },
  },
  {
    id: "graduation-cap",
    name: "Graduation",
    eventType: "graduation",
    aspectRatio: 4 / 5,
    canvas: { width: 1080, height: 1350 },
    background: {
      type: "gradient",
      from: "#0d1b2a",
      to: "#1b263b",
    },
    textLayers: [
      {
        id: "title",
        defaultText: "Class of 2026",
        x: 0.5,
        y: 0.24,
        fontSize: 48,
        fontFamily: "Cormorant Garamond",
        fontWeight: "600",
        color: "#ffd700",
        textAlign: "center",
        maxWidth: 0.85,
      },
      {
        id: "date",
        defaultText: "Graduation Ceremony",
        x: 0.5,
        y: 0.4,
        fontSize: 22,
        fontFamily: "Cormorant Garamond",
        color: "#e0e0e0",
        textAlign: "center",
        maxWidth: 0.85,
      },
      {
        id: "tagline",
        defaultText: "Please join us to celebrate",
        x: 0.5,
        y: 0.53,
        fontSize: 18,
        fontFamily: "Cormorant Garamond",
        color: "#aab4c0",
        textAlign: "center",
        maxWidth: 0.85,
      },
    ],
    objectSlots: [
      { id: "top", assetId: "divider-line", x: 0.5, y: 0.1, scale: 0.5, default: true },
    ],
    photoSlot: { x: 0.5, y: 0.72, width: 0.3, height: 0.3, shape: "circle" },
  },
  {
    id: "holiday-festive",
    name: "Holiday party",
    eventType: "party",
    aspectRatio: 4 / 5,
    canvas: { width: 1080, height: 1350 },
    background: {
      type: "gradient",
      from: "#1a3c34",
      to: "#0d2818",
    },
    textLayers: [
      {
        id: "title",
        defaultText: "Holiday Celebration",
        x: 0.5,
        y: 0.22,
        fontSize: 46,
        fontFamily: "Cormorant Garamond",
        fontWeight: "600",
        color: "#f0e6d3",
        textAlign: "center",
        maxWidth: 0.85,
      },
      {
        id: "date",
        defaultText: "December 21 at 7 PM",
        x: 0.5,
        y: 0.38,
        fontSize: 22,
        fontFamily: "Cormorant Garamond",
        color: "#c4a35a",
        textAlign: "center",
        maxWidth: 0.85,
      },
      {
        id: "tagline",
        defaultText: "Eat, drink, and be merry",
        x: 0.5,
        y: 0.52,
        fontSize: 18,
        fontFamily: "Cormorant Garamond",
        color: "#a0c4a0",
        textAlign: "center",
        maxWidth: 0.85,
      },
    ],
    objectSlots: [
      { id: "divider", assetId: "divider-line", x: 0.5, y: 0.65, scale: 0.5, default: true },
    ],
  },
  {
    id: "corporate-modern",
    name: "Corporate event",
    eventType: "generic",
    aspectRatio: 4 / 5,
    canvas: { width: 1080, height: 1350 },
    background: {
      type: "solid",
      color: "#ffffff",
    },
    textLayers: [
      {
        id: "title",
        defaultText: "Annual Conference",
        x: 0.5,
        y: 0.25,
        fontSize: 42,
        fontFamily: "Cormorant Garamond",
        fontWeight: "600",
        color: "#1a1a1a",
        textAlign: "center",
        maxWidth: 0.85,
      },
      {
        id: "date",
        defaultText: "March 15, 2026 | 9:00 AM",
        x: 0.5,
        y: 0.4,
        fontSize: 20,
        fontFamily: "Cormorant Garamond",
        color: "#555555",
        textAlign: "center",
        maxWidth: 0.85,
      },
      {
        id: "tagline",
        defaultText: "Innovation. Leadership. Growth.",
        x: 0.5,
        y: 0.53,
        fontSize: 18,
        fontFamily: "Cormorant Garamond",
        color: "#888888",
        textAlign: "center",
        maxWidth: 0.85,
      },
    ],
    objectSlots: [
      { id: "top", assetId: "divider-line", x: 0.5, y: 0.1, scale: 0.6, default: true },
      { id: "bottom", assetId: "divider-line", x: 0.5, y: 0.9, scale: 0.6, default: true },
    ],
  },
  {
    id: "anniversary-gold",
    name: "Anniversary",
    eventType: "generic",
    aspectRatio: 4 / 5,
    canvas: { width: 1080, height: 1350 },
    background: {
      type: "gradient",
      from: "#faf6ef",
      to: "#f0e8d8",
    },
    textLayers: [
      {
        id: "title",
        defaultText: "25 Years Together",
        x: 0.5,
        y: 0.22,
        fontSize: 46,
        fontFamily: "Cormorant Garamond",
        fontWeight: "600",
        color: "#8b6914",
        textAlign: "center",
        maxWidth: 0.85,
      },
      {
        id: "date",
        defaultText: "Join us for dinner",
        x: 0.5,
        y: 0.38,
        fontSize: 22,
        fontFamily: "Cormorant Garamond",
        color: "#6b5b3e",
        textAlign: "center",
        maxWidth: 0.85,
      },
      {
        id: "tagline",
        defaultText: "Celebrating love and memories",
        x: 0.5,
        y: 0.51,
        fontSize: 18,
        fontFamily: "Cormorant Garamond",
        color: "#8a7a60",
        textAlign: "center",
        maxWidth: 0.85,
      },
    ],
    objectSlots: [
      { id: "top", assetId: "divider-line", x: 0.5, y: 0.08, scale: 0.5, default: true },
      { id: "bottom", assetId: "divider-line", x: 0.5, y: 0.92, scale: 0.5, default: true },
    ],
    photoSlot: { x: 0.5, y: 0.7, width: 0.32, height: 0.32, shape: "circle" },
  },
  {
    id: "housewarming-cozy",
    name: "Housewarming",
    eventType: "generic",
    aspectRatio: 4 / 5,
    canvas: { width: 1080, height: 1350 },
    background: {
      type: "gradient",
      from: "#fdf5e6",
      to: "#f5e6c8",
    },
    textLayers: [
      {
        id: "title",
        defaultText: "Welcome Home",
        x: 0.5,
        y: 0.24,
        fontSize: 46,
        fontFamily: "Cormorant Garamond",
        fontWeight: "600",
        color: "#4a3728",
        textAlign: "center",
        maxWidth: 0.85,
      },
      {
        id: "date",
        defaultText: "Housewarming Party",
        x: 0.5,
        y: 0.4,
        fontSize: 22,
        fontFamily: "Cormorant Garamond",
        color: "#6b5b4a",
        textAlign: "center",
        maxWidth: 0.85,
      },
      {
        id: "tagline",
        defaultText: "Come see our new place!",
        x: 0.5,
        y: 0.53,
        fontSize: 18,
        fontFamily: "Cormorant Garamond",
        color: "#8a7a6a",
        textAlign: "center",
        maxWidth: 0.85,
      },
    ],
    objectSlots: [
      { id: "divider", assetId: "divider-line", x: 0.5, y: 0.65, scale: 0.5, default: true },
    ],
  },
];

export function getDesignTemplate(id: string): DesignTemplate {
  return DESIGN_TEMPLATES.find((t) => t.id === id) ?? DESIGN_TEMPLATES[0];
}
